SELECT * FROM customers limit 20 
--Q1. What is the total revenue generated by male and female customer ?

SELECT gender,SUM(purchase_amount) AS TotalRevenue
from customers
group by gender 

--Q2. Whiich customer used discount code but still spent more than the average purchase amount?


SELECT customerid,purchase_amount
from customers
WHERE discountapplied = 'Yes' and purchase_amount >= ( SELECT AVG(purchase_amount) from customers)

--Q3.Which are the top 5 oroduct with highest review rating

SELECT itempurchased, ROUND(AVG(reviewrating::int),2) AS Rating 
from customers
group BY itempurchased
ORDER BY AVG(reviewrating) DESC
limit 5

--Q4. Compare the average Purchase amount between Standard and Express shipping

SELECT shippingtype,
ROUND(AVG(purchase_amount),2) AS averagecost
FROM customers 
WHERE shippingtype IN ('Express','Standard')
GROUP BY shippingtype 

--Q5.Do subscribed cutomers spend more ? Compare average spend and total revenue between subscribers and non-subscribers

SELECT subscriptionstatus,
COUNT(customerid) as total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customers
group by subscriptionstatus
ORDER BY total_revenue,avg_spend DESC

--Q6. Which 5 products have the highest percentage of purchase with discounts applied?

SELECT itempurchased,
ROUND(100 * SUM(CASE WHEN discountapplied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customers
group by itempurchased
ORDER BY discount_rate DESC
LIMIT 5

--Q7. Segment customers into New,Returning, and Loyal based on their total number 
--of previous purchases, and show the count of each sgment.

WITH customer_type AS(
SELECT customerid, previouspurchases,
CASE
	WHEN previouspurchases = 1 then 'NEW'
	WHEN previouspurchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'loyal'
	END AS customersegment
FROM customers)

SELECT customersegment,COUNT(*) as "Number of Customers"
FROM customer_type
GROUP BY customersegment



--Q8. What are the top 3 most purchased products within each category

WITH item_counts AS (
SELECT category,
itempurchased,
COUNT(customerid) AS total_orders,

ROW_NUMBER() OVER (PARTITION BY category order by count(customerid)DESC) AS item_rank
FROM customers
GROUP BY category , itempurchased
)

SELECT item_rank,category,itempurchased,total_orders 
FROM item_counts
WHERE item_rank <=3

--Q9. Are customers who are repeat buyers also likely to subscribers?

SELECT subscriptionstatus,
COUNT(customerid) as repeat_buyers
FROM customers
WHERE previouspurchases>5
GROUP BY subscriptionstatus 

--Q10. What is the revenue contriburion by age group

SELECT age_group,
SUM(purchase_amount) AS totalrevenue
FROM customers
GROUP BY age_group
ORDER BY totalrevenue DESC



	
